### ISSUE TITLE
Cannot change watch folder via settings.json

### ISSUE THREAD

**Issue by zilexa** [linuxserver/docker-transmission#100]
------------------------------

## Expected Behavior
You should be able to change settings via the settings.json file, only modifying it after stopping the container. 

## Current Behavior
All modified settings are present EXCEPT `watch-dir`, it's value is back to default `"/watch"`.

## Steps to Reproduce
1. Stop the container.
2. Wait until it is stopped.
3. Edit the config file via the folder that was mounted during container creation, ie: /$home/docker/transmission/config/settings.json
4. Edit multiple values including watch-dir.
5. Save. 
6. Start the container, wait till its started. 
7. Open webUI to check if its running.
8. Open settings.json again to verify modifications persisted.

## Environment
**OS: Ubuntu 19.10**
**CPU architecture: x86_64**
**How docker service was installed:docker-compose.yml**      

## Command used to create docker container)
```
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=admin
      - PASS=removed
    volumes:
      - ${USERDIR}/docker/transmission/config:/config
      - ${USERDIR}/Media:/media
```
