### ISSUE TITLE
Parameters for transmission settings

### ISSUE THREAD

**Issue by rradar** [linuxserver/docker-transmission#107]
## Expected Behavior

It would be nice to have (extra) parameters to set various transmission settings

for example:
```yaml
  transmission:
    container_name: transmission
    image: linuxserver/transmission:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - USER=superuser
      - PASS=superpassword
      - TRANSMISSION_UPLOAD_LIMIT=1000
      - TRANSMISSION_UPLOAD_LIMIT_ENABLED=1
      - TRANSMISSION_DOWNLOAD_LIMIT=1000
      - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=1
      - TRANSMISSION_ALT_SPEED_UP=500
      - TRANSMISSION_ALT_SPEED_DOWN=500
      - TRANSMISSION_RATIO_LIMIT=3
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_ENCRYPTION=2
```

## Current Behavior
Beside setting the `USER` and `PASS` no transmission specific settings are able to set via docker-compose.yaml at the moment - if I'm right?

This makes it impossible for me to have a reproducible setup with docker-compose as I'm forced to the stock settings.

Here is a link to a [transmission-openvpn docker ](https://github.com/haugene/docker-transmission-openvpn)which includes transmission settings: https://haugene.github.io/docker-transmission-openvpn/arguments/#transmission_configuration_options
