### ISSUE TITLE
Don't  create a /downloads volume when there is no mapping for it

### ISSUE THREAD

**Issue by zilexa** [linuxserver/docker-transmission#110]
## Expected Behavior
I do not expect a docker volume to be created by Transmission at /downloads when I did not state a mapping for it via docker command or docker-compose. Note this  does not happen with other LinuxServer containers like Sonarr and Bazarr. They run fine with only a single mapping. 

## Current Behavior
a docker volume /downloads is created. 
This should happen only when a mapping has been created for it. 

## Steps to Reproduce
When my docker compose looks like this, I do not expect a /downloads volume:
```
    volumes:
      - $HOME/docker/transmission/config:/config
      - /mnt/pool/Media:/media
```
I can simply set the correct complete/incomplete folders via the webUI settings:
`/media/incoming/complete`
`/media/incoming/incomplete`
Also Radarr, Bazarr and Sonarr have the mountpoint at /mnt/pool/Media:/media and their webUI is looking at: 
`/media/TVshows`
`/media/Movies`
This all works fine. Since they are all mapped by a single directory, Sonarr/Bazarr can use hardlinks for files seeding via Transmission. 

## Environment
**OS: Ubuntu Budgie 19.10
**CPU architecture:** x86_64 
**How docker service was installed:**      
Via docker-compose.yml, example of Transmission and Sonarr:
```
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=admin
      - PASS=$PW_MEDIA
    volumes:
      - $HOME/docker/transmission/config:/config
      - /mnt/pool/Media:/media
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - $HOME/docker/sonarr/config:/config
      - /mnt/pool/Media:/media
```
