### ISSUE TITLE
RPC should allow connections from localhost and docker network by default.

### ISSUE THREAD

**Issue by deafmute1** [linuxserver/docker-transmission#133]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Transmission RPC should allow connections from localhost and docker network by default.

This would allow you to access the HTTP and RPC endpoints using localhost/loopback or (more importantly) over a internal docker network (using the service/host name). This makes sense in the context where you likely are including things like sonarr or radarr within the same docker stack, and using the internal docker network for communication instead of having to hit the host's interface unnecessarily. All this requies doing is changing "rpc-host-whitelist-enabled" to false in settings.json, and I think this should be the default setting for a docker environment especially as this option isn't documented anywhere and I had to trial and error modiy settings.json to figure it out.
## Current Behavior

Transmission only only accepts connections from the host's IP LAN network interfaces.

## Steps to Reproduce
1. Try to use docker service name as host in sonarr/radarr/etc
2. Doesn't work
3. Change "rpc-host-whitelist-enabled" to false
4. Works.

## Environment
**OS:** Debian 10/OMV 5
**CPU architecture:** x86_64
**How docker service was installed:** docker hub repo

## Command used to create docker container (run/create/compose/screenshot)
 

``` yaml
    transmission-sys2:
        environment:
          - PGID=1001
          - PUID=1001    
          - UMASK_SET=002
        dns:
          - 1.1.1.1
          - 1.0.0.1
        image: linuxserver/transmission:latest
        volumes:
            - /var/ddata/autoget/transmission-sys:/config
            - /export/mergerfs/downloads/sys:/downloads
        networks:
            - internal
        ports:
            - 9091:9091 #webui and daemon
            - 51413:51413 #bt
            - 51413:51413/udp #bt
        deploy:
            restart_policy:
                condition: on-failure
                delay: 60s
                max_attempts: 5  
```
