### ISSUE TITLE
Directory watch does not work on Windows

### ISSUE THREAD

**Issue by davidshen84** [linuxserver/docker-transmission#136]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Adding a torrent file to the watch directory, *transmission* should pick up the file and start downloading it.

## Current Behavior
Nothing happens

## Steps to Reproduce

1. Create a container on Windows with watch directory
2. Put a torrent file in the *watch* directory

## Environment
**OS:** Windows 10, build 19041.610
**CPU architecture:** x86_64
**How docker service was installed:** official

## Command used to create docker container (run/create/compose/screenshot)

**Only the transmission service part of the docker-compose.yaml file.**

```
  transmission:
    container_name: transmission
    image: ghcr.io/linuxserver/transmission:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Australia/Sydney"
      TRANSMISSION_WEB_HOME: "/combustion-release/" #optional
      USER: user #optional
      PASS: pass #optional
    volumes:
      - "transmission:/config"
      - "/mnt/e/transmission/downloads:/downloads"
      - "/mnt/e/transmission/watch:/watch"
    ports:
      - 9091:9091
      - 51413:51413/tcp
      - 51413:51413/udp
    restart: unless-stopped
```
## Docker logs

*Nothing happens after putting a torrent file in the watch directory.*
