### ISSUE TITLE
Wrong owner for settings.json 

### ISSUE THREAD

**Issue by alfonder** [linuxserver/docker-transmission#162]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When env vars PUID and PGID are set, those values should be used for created/modified files owner/group.

## Current Behavior
Files settings.json and dht.dat get 911/1001 owner/group and then are not accessible for transmission daemon. The daemon uses a default configuration.

## Steps to Reproduce

This is definitely a regression, because the issue exists on version 3.00-r2-ls86 and is absent on version 3.00-r2-ls80
1. docker pull linuxserver/transmission:3.00-r2-ls86
2. docker-compose up -d
3. ls -ln /tmp/config
```bash
total 16
drwxr-sr-x 1 1000  100    0 Jun 17  2019 blocklists
-rwxr-xr-x 1 1000  100  553 Jul  2  2018 blocklist-update.sh
-rw------- 1  911 1001  532 Apr 27 22:47 dht.dat
drwxrwsr-x 1 1000  100 1316 Apr 27 22:20 resume
-rw------- 1  911 1001 2257 Apr 27 22:47 settings.json
-rw------- 1 1000  100  162 Apr 27 22:20 stats.json
drwxrwsr-x 1 1000  100 1344 Apr 27 21:30 torrents
```

## Environment
**OS:** Debian GNU/Linux 10 (buster)
**CPU architecture:** x86_64
**How docker service was installed:**
From Debian repo
Package: docker-ce
Version: 5:20.10.6~3-0~debian-buster

## Command used to create docker container (run/create/compose/screenshot)
```yaml
version: '3'

networks:
  default:
    external:
      name: network

services:
  transmission:
    container_name: transmission
    hostname: tr.dckr
    image: linuxserver/transmission:3.00-r2-ls86
    restart: unless-stopped
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /tmp/config:/config
      - /tmp/downloads:/downloads
    environment:
      - TZ="Europe/Moscow"
      - PUID=1000
      - PGID=100
```

## Docker logs
None
