### ISSUE TITLE
Port forwarding does not work with latest versions based on alpine 3.13+

### ISSUE THREAD

**Issue by doman18** [linuxserver/docker-transmission#165]
Despite of proper port exposed by container and proper port forwarding set on router and positive result from https://www.yougetsignal.com/tools/open-ports/ in transmission GUI port is marked as Closed. 
When downgraded to 3.00-r0-ls75 (last version based on alpine 3.12) port forwarding starts to work fine. No additional steps needed.
Additional info (maybe usefull?):
I had issuses with 3.13+ when tried to use it as base for my ipmitools project. It had issues with recognizing host DNS and thus could not install any additional packages. Downgrading to 3.12 helped too.
------------------------------

## Steps to Reproduce
Just pull image with :latest tag or without tag at all.

## Environment
**OS:** Raspbian
**CPU architecture:** arm64
**How docker service was installed:**
From convenience script, according to official docker documentation
 Docker version 20.10.7, build f0df350
```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo ./get-docker.sh 2>&1 | tee -a get-docker.log
```

## Command used to create docker container (run/create/compose/screenshot)
```
docker-compose up -d
```
docker-compose.yml
```
# https://hub.docker.com/r/linuxserver/transmission

version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission:3.00-r0-ls75
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ${TRANSMISSION_VOLUME_CONFIG}:/config
      - ./settings/settings.json:/config/settings.json
      - ${TRANSMISSION_VOLUME_DOWNLOADS}:/downloads
      - ${TRANSMISSION_VOLUME_WATCH}:/watch
    ports:
      - ${TRANSMISSION_EXTPORT_WEB}:9091
      - ${TRANSMISSION_EXTPORT_TCP}:51413
      - ${TRANSMISSION_EXTPORT_UDP}:51413/udp
    restart: always
    networks:
      - 'rev_proxy_net'
  
networks:
  rev_proxy_net:
      external:
        name: ${PROXY_NETWORK}
```
.env
```
TRANSMISSION_VOLUME_CONFIG=/home/pi/volumes/transmission/config
TRANSMISSION_VOLUME_DOWNLOADS=/mnt/sda1/volumes/transmission/downloads
TRANSMISSION_VOLUME_WATCH=/home/pi/volumes/transmission/watch
# ports
TRANSMISSION_EXTPORT_WEB=9091
TRANSMISSION_EXTPORT_TCP=51413
TRANSMISSION_EXTPORT_UDP=51413
PROXY_NETWORK=reverse_proxy_network
```
settings.json
```
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/downloads/complete",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/downloads/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": false,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "censored",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "transmission",
    "rpc-whitelist": "",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 2,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true,
    "watch-dir": "/watch",
    "watch-dir-enabled": true
}

```
