### ISSUE TITLE
Transmission web-ui does not save to settings.json

### ISSUE THREAD

**Issue by drwb** [linuxserver/docker-transmission#180]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When editing settings in the (flood-for-transmission or default) ui, clicking save should persist the settings in settings.json to be read on restart.

## Current Behavior
Editing and saving settings saves them until restart, but old settings.json is loaded on restart.

## Steps to Reproduce
1. Edit something in settings
2. Click save
3. Restart container
4. Check settings or cat config.json

## Environment
**OS:** Ubuntu 20.04.3 LTS
**CPU architecture:** linux/amd64
**How docker service was installed:** apt-get

## Command used to create docker container (run/create/compose/screenshot)

<img width="587" alt="Screenshot 2021-10-21 at 10 24 02" src="https://user-images.githubusercontent.com/16479230/138249738-936f1d5a-4449-489c-a15e-d1edd6822066.png">

ls -ln of /config/
<img width="426" alt="Screenshot 2021-10-21 at 10 27 45" src="https://user-images.githubusercontent.com/16479230/138250354-07b1b11a-730f-434a-b72a-94d15cc4133f.png">

**Comment by drizuid** [comment]
please disable flood-for-transmission and re-test

**Comment by kcstllo** [comment]
I am seeing the same issue and I have no web UI.

**Comment by drizuid** [comment]
> I am seeing the same issue and I have default web UI.

thanks for checking! can you provide your compose and logs as well?

**Comment by kcstllo** [comment]
> > I am seeing the same issue and I have default web UI.
> 
> thanks for checking! can you provide your compose and logs as well?

Of course. Compose is below. What logs are you looking for?

```
x-default-policy:
  &default-policy
  restart: unless-stopped

services:
  transmission:
    <<: *default-policy
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    network_mode: <service>
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      # Authentication
      - USER=<username>
      - PASS=<password>
      - WHITELIST=<ips>
    volumes:
      - transmission_config:/config
      - transmission_data:/downloads
      - transmission_data:/watch
      - media_data:/media
    # Exposed over service.
    # ports:
      # - 9091:9091
      # - 51413:51413
      # - 51413:51413/udp
    networks:
      frontend:
        ipv4_address: <staticip>

networks:
  frontend:
    name: frontend
    driver: bridge
    ipam:
      config:
      - subnet: <subnet>
      driver: default

volumes:
  transmission_data:
    external: true
  transmission_config:
    external: true
  media_data:
    external: true
```
