### ISSUE TITLE
Several errors regarding Exec format error

### ISSUE THREAD

**Issue by vuurvoske** [linuxserver/docker-transmission#181]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
The container / deployment should not have issues with permissions

## Current Behavior
lots of errors regarding persmission and spawning of files/ dirs

## Steps to Reproduce
Build the latest container build.
This does not happen in linuxserver/transmission:amd64-2021.10.07

## Environment
**OS:** k3s (on debian 10 VM, which is run on proxmox 7.0.3)
**CPU architecture:** amd64
**How docker service was installed:**
embedded in k3s deployment, official image from linuxserver/transmission(:latest)

## Command used to create docker container (run/create/compose/screenshot)
transmission/deploy.yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      restartPolicy: Always
      volumes:
        - name: iscsi-config-transmission
          iscsi:
            targetPortal: <someip>:3260
            iqn: <someiqnnumber>.truenas.ctl:k3s-transmission
            lun: 9
            fsType: xfs
            readOnly: false
            chapAuthSession: false
        - name: nfs-complete
          nfs: 
            server: <someip>
            path: /mnt/storagepool/complete
        - name: nfs-incomplete
          nfs: 
            server: <someip>
            path: /mnt/storagepool/incomplete
        - name: nfs-leesmap
          nfs: 
            server: <someip>
            path: /mnt/storagepool/leesmap
      containers:
      - name: transmission
        image: linuxserver/transmission
        imagePullPolicy: "Always"
        env:                      
        - name: PGID
          value: "1000" # < group "user"
        - name: PUID
          value: "1000" # < user "docker"
        - name: TZ
          value: Europe/Amsterdam
        ports:
        - containerPort: 9091
          name: http-9091
          protocol: TCP
        - containerPort: 51413
          name: seed-51413
          protocol: TCP
        - containerPort: 51413
          name: seed-51413-udp
          protocol: UDP
        volumeMounts:
            - name: iscsi-config-transmission
              mountPath: "/config"
            - name: nfs-complete
              mountPath: "/downloads"
            - name: nfs-incomplete
              mountPath: "/incomplete-downloads"
            - name: nfs-leesmap
              mountPath: "/watched"
```

## Docker logs
```bash
k logs transmission-7f88dddfdf-b4pt4
foreground: warning: unable to spawn /docker-mods: Exec format error
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/01-envfile: Exec format error
[cont-init.d] 01-envfile: exited 127.
[cont-init.d] 10-adduser: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/10-adduser: Exec format error
[cont-init.d] 10-adduser: exited 127.
[cont-init.d] 20-config: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/20-config: Exec format error
[cont-init.d] 20-config: exited 127.
[cont-init.d] 90-custom-folders: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/90-custom-folders: Exec format error
[cont-init.d] 90-custom-folders: exited 127.
[cont-init.d] 99-custom-files: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/99-custom-files: Exec format error
[cont-init.d] 99-custom-files: exited 127.
[cont-init.d] done.
[services.d] starting services
s6-supervise (child): fatal: unable to exec run: Exec format error
s6-supervise transmission: warning: unable to spawn ./run - waiting 10 seconds
[services.d] done.
s6-supervise (child): fatal: unable to exec run: Exec format error
s6-supervise cron: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise cron: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Exec format error
s6-supervise (child): fatal: unable to exec run: Exec format error
s6-supervise transmission: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise transmission: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Exec format error
s6-supervise cron: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Exec format error
s6-supervise cron: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Exec format error
s6-supervise transmission: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Exec format error
```

## Testing:
- several rebuilds of container / deployment
- deleted iscsi config vol, this didnt help
- used previous tag: problem isn't showing
