### ISSUE TITLE
Flood for Transmission - Mobile interface missing

### ISSUE THREAD

**Issue by tamet83** [linuxserver/docker-transmission#190]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Hi, I successfully installed Transmission with Flood for Transmission interface.
It runs ok on desktop but it doesn't provide a mobile interface.

I noticed that on the maintainer page this feature has been [implemented](https://github.com/johman10/flood-for-transmission/pull/126) 

I just don't know if you're merging code from that repository or you're implementing it by yourself.

In any case, there is any chance to implement mobile view also on your image?

## Environment
**OS:** Docker inside Proxmox 7 container
**CPU architecture:** x86_64
**How docker service was installed:**
I used the officiale dockerhub image.

## Command used to create docker container (run/create/compose/screenshot)
This is my docker-compose:

```yaml
# TRANSMISSION
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/ #optional
    volumes:
      - /transmission:/config
      - /media/download:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
```
