### ISSUE TITLE
Init fails on chown for NFS directories

### ISSUE THREAD

**Issue by leukanos** [linuxserver/docker-transmission#214]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Transmission should work correctly with mounted NFS folder.
(it was working correctly for version linuxserver/transmission:3.00-r5-ls138)

## Current Behavior
`init-transmission-config` fails on `chown` for **complete** and **incomplete** folders:
```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

chown: changing ownership of '/downloads/complete': Operation not permitted
chown: changing ownership of '/downloads/incomplete': Operation not permitted
s6-rc: warning: unable to start service init-transmission-config: command exited 1
```

## Steps to Reproduce

1. Use the mounted NFS `download` folder (or mounted complete/incomplete folders inside download) as download volume
2. Run docker-compose

## Environment
**OS:** Ubuntu 22.04 LXC on Proxmox
**CPU architecture:** x86_64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)
```
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=leukanos #optional
      - PASS=pinky-winky #optional
    volumes:
      - /home/docker/arr/transmission/data:/config
      - /home/docker/downloads:/downloads
      - /home/docker/arr/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"    
```
