### ISSUE TITLE
[BUG] <Cannot access GUI after updated to 4.0.0.5.r01 in ASUSTOR NAS>

### ISSUE THREAD

**Issue by RaysonYeungHK** [linuxserver/docker-transmission#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

none of the following url can access the GUI anymore

http://x.x.x.x:29091/transmission/web/
http://x.x.x.x:29091/transmission/
http://x.x.x.x:29091/

it shows ERR_CONNECTION_REFUSED

before the update, this URL works fine
http://x.x.x.x:29091/transmission/web/

### Expected Behavior

Either one of the URL should be able to open the GUI

### Steps To Reproduce

1. Click on the Transmission app of the ADM Portal of the NAS
2. Confirm the error

### Environment

```markdown
- OS: ASUSTOR ADM 4.2.0.RE71
- How docker service was installed: ASUSTOR App Central
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by thespad** [comment]
Need at least the container logs or there's very little we can do to diagnose the problem.

**Comment by scoiattolo49** [comment]
This issue is present since the first release of version 4.0.0
It was announced in the release notes
`Remove bundled 3rd party UI packages`

So this is not a bug but a deliberate choice by the developers (not sure why this was done but I'm sure that there are reasons).

To solve you have to add your own web interface and refer to it using the TRANSMISSION_WEB_HOME variable. Or you can choose another transmission mod that includes a web interface

**Comment by nickv2002** [comment]
For other's ref here's what I did:

```yaml
version: "3"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VIRTUAL_HOST=transmission.local
      - VIRTUAL_PORT=9091
      - TRANSMISSION_WEB_HOME=/config/transmission-web-control/src/ #optional
    volumes:
      - /nas/docker-data/config/appdata/transmission:/config
      - /etc/localtime:/etc/localtime:ro
      - /nas/Torrents/Watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  ```
  
Then, to download the WebUI files, I went to `/nas/docker-data/config/appdata/transmission` on my host system, and did:
  
```
git clone --depth 1 https://github.com/ronggang/transmission-web-control.git
```
