### ISSUE TITLE
[BUG] Image should not be built with assertions enabled

### ISSUE THREAD

**Issue by rpatterson** [linuxserver/docker-transmission#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running the image with torrents or other conditions that would trigger assertion errors do so [as can be seen in the containers output](https://github.com/transmission/transmission/issues/4878#issue-1583320124).

### Expected Behavior

[End user builds should not enable assertions](https://github.com/transmission/transmission/issues/4878#issuecomment-1430754614) and as such this container image should not run with assertions enabled.

### Steps To Reproduce

Run this container image with a set of torrents that trigger one or more assertion errors and note the errors.  See [this upstream issue](https://github.com/transmission/transmission/issues/4878#issue-1583320124) for an example that multiple users have observed.

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- How docker service was installed: a `./docker-compose.yml` config including a bind mount volume containing existing torrents
```

### CPU architecture

x86-64

### Docker creation

From `./docker-compose.yml`:

```yaml
version: "3.8"
services:
  transmission:
    image: "linuxserver/transmission"
    container_name: "transmission"
    environment:
      TZ: "${TZ:-America/Los_Angeles}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-100}"
      USER: "${TRANSMISSION_USER:-transmission}"
      PASS: "${TRANSMISSION_PASS}"
    volumes:
      - "./transmission/config/:/config/"
      - type: bind
        source: "${DOWNLOAD_VOLUME:-/media/Library/}"
        target: "${DOWNLOAD_VOLUME:-/media/Library/}"
        bind:
          propagation: "shared"
```

### Container logs

```bash
...
transmission  | [custom-init] No custom files found, skipping...                                                                                                           
transmission  | assertion failed: bit_count_ == 0 || n <= bit_count_ (/home/buildozer/aports/community/transmission/src/transmission-4.0.0/libtransmission/bitfield.cc:233)
transmission  | ./run: line 6:   161 Aborted                 s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 9091" s6-setuidgid abc /usr/bin/transmission-daemon -g 
/config -c /watch -f                                                                                                                                                       
...
```
