### ISSUE TITLE
[BUG] Cann't set password from secret

### ISSUE THREAD

**Issue by Buntelrus** [linuxserver/docker-transmission#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using FILE__PASS env in the container a proper PASS env with the correct password is created. But transmission is ignoring it and the password is just "". 

### Expected Behavior

Transmission password should equal to the content of the proper secret.

### Steps To Reproduce

my conf:
```
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
#      - TRANSMISSION_WEB_HOME= #optional
      - USER=buntel
      - FILE__PASS=/run/secrets/password # unfortunately, this is not working
#      - WHITELIST= #optional
#      - PEERPORT= #optional
#      - HOST_WHITELIST= #optional
    secrets:
      - password
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
```

### Environment

```markdown
- OS: Arch, Ubuntu
- How docker service was installed: package manager, official Rekommandation
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up -d
```

### Container logs

```bash
transmission  | [migrations] started
transmission  | [migrations] no migrations found
transmission  | [env-init] PASS set from FILE__PASS
transmission  | ───────────────────────────────────────
transmission  | 
transmission  |       ██╗     ███████╗██╗ ██████╗ 
transmission  |       ██║     ██╔════╝██║██╔═══██╗
transmission  |       ██║     ███████╗██║██║   ██║
transmission  |       ██║     ╚════██║██║██║   ██║
transmission  |       ███████╗███████║██║╚██████╔╝
transmission  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
transmission  | 
transmission  |    Brought to you by linuxserver.io
transmission  | ───────────────────────────────────────
transmission  | 
transmission  | To support LSIO projects visit:
transmission  | https://www.linuxserver.io/donate/
transmission  | 
transmission  | ───────────────────────────────────────
transmission  | GID/UID
transmission  | ───────────────────────────────────────
transmission  | 
transmission  | User UID:    1000
transmission  | User GID:    1000
transmission  | ───────────────────────────────────────
transmission  | 
transmission  | sed: unsupported command "
transmission  | # do daily/weekly/monthly maintenance
transmission  | # min   hour    day     month   weekday command
transmission  | */15    *       *       *       *       run-parts /etc/periodic/15min
transmission  | 0       *       *       *       *       run-parts /etc/periodic/hourly
transmission  | 0       2       *       *       *       run-parts /etc/periodic/daily
transmission  | 0       3       *       *       6       run-parts /etc/periodic/weekly
transmission  | 0       5       1       *       *       run-parts /etc/periodic/monthly
transmission  | 
transmission  | # run daily blocklist update
transmission  | 0 3 * * * /app/blocklist-update.sh 2>&1
transmission  | cp: not replacing '/config/crontabs/root'
transmission  | [custom-init] No custom files found, skipping...
transmission  | [ls.io-init] done.
```

**Comment by aptalca** [comment]
The secret is probably not created correctly. See the docker docs to see how to create it properly: https://docs.docker.com/engine/swarm/secrets/#simple-example-get-started-with-secrets

**Comment by Buntelrus** [comment]
@aptalca 

I define my secret as follows:
```
secrets:
  privatekey:
    file: ./privatekey.key
  password:
    file: ./password.txt
```
regarding to the (documentation)[https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets] this should be correct. Furthermore I can access the the correct password with ` docker compose exec transmission cat /run/secrets/password` but `echo $PASS` is empty.
