### ISSUE TITLE
[BUG] Watch folder not working with Docker Windows

### ISSUE THREAD

**Issue by MatrixRonny** [linuxserver/docker-transmission#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add a torrent to the watch folder (manual paste), it is not taken into account. I need to issue `docker-compose stop` and then `docker-compose start`. Otherwise, the added torrent file does not get the .added suffix to its name, nor added to config/torrents folder.

### Expected Behavior

The torrent file is added immediately to the config/torrents folder.

### Steps To Reproduce

1. Create the docker-compose.yml file with the contents bellow:
2. Create config, downloads and watch folders next to the docker-compose file.
3. Run `docker-compose up`
4. Add a torrent to the watch folder.

### Environment

```markdown
- OS: Windows 10 Pro
- I am using Docker Desktop for Windows (4.19.0) downloaded from https://www.docker.com/products/docker-desktop/
- Docker was configured to use WSL2
- I noticed that files in config folder (created by transmission-Docker) are owned by my logged on Windows user 
- It is not a network issue, since torrents work after recreating the container.
```

### CPU architecture

x86-64

### Docker creation

``` YML
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
