### ISSUE TITLE
[FEAT] Add natpmpc to enable Proton VPN port forwarding

### ISSUE THREAD

**Issue by sebdanielsson** [linuxserver/docker-transmission#248]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add natpmpc to image.

### Reason for change

natpmpc is needed for port forwarding with Proton VPN.
https://protonvpn.com/support/port-forwarding-manual-setup/
https://www.reddit.com/r/ProtonVPN/comments/10owypt/successful_port_forward_on_debian_wdietpi_using/

**Comment by Roxedus** [comment]
You can install this yourself. https://github.com/linuxserver/docker-mods/tree/universal-package-install

The functionality you want is outside of the scope of this repository.

**Comment by jordanpotter** [comment]
Hey @sebdanielsson (and whomever else reads this in the future), I made a Docker mod for you 😄 

Just add the `jordanpotter/docker-mods:transmission-nat-pmp` Docker mod. For example:

```
docker run -d \
  --name=transmission \
  -e DOCKER_MODS="jordanpotter/docker-mods:transmission-nat-pmp"
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -p 9091:9091 \
  -p 51413:51413 \
  -p 51413:51413/udp \
  -v /path/to/data:/config \
  -v /path/to/downloads:/downloads \
  -v /path/to/watch/folder:/watch \
  --restart unless-stopped \
  lscr.io/linuxserver/transmission:latest
```

You can read the source code [here](https://github.com/jordanpotter/docker-mods/tree/main/transmission-nat-pmp). It relies on a Go application I made to start a NAT-PMP client and update Transmission's peer port when the NAT port changes ([here](https://github.com/jordanpotter/transmission-nat-pmp/blob/main/main.go)).

I haven't gotten around to writing documentation yet. But if you have any issues, feel free to file a bug in the [jordanpotter/docker-mods](https://github.com/jordanpotter/docker-mods) repo.

**Comment by sebdanielsson** [comment]
Wow thank you! Can’t wait to try this out!😃

**Comment by PHLAK** [comment]
Jut added the `jordanpotter/docker-mods:transmission-nat-pmp` docker mod and it appears to be working great! Thank you @jordanpotter!

<img src="https://github.com/linuxserver/docker-transmission/assets/53531/df8b59eb-efeb-4d9f-a375-f831283ebfcc" width="50%">

**Comment by alexg-k** [comment]
Hi @jordanpotter, your docker mod looks just what I need. However, I cannot get it overwrite the default listening port. I added your mod, but it is does not seem to have any effect (nothings seems to be pulled?). It is my first time using a docker mod, so any help is appreciated.
This is an excerpt of my `docker-compose.yaml`:
```
[...]
transmission:
    image:  linuxserver/transmission
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - DOCKER_MODS=jordanpotter/docker-mods:transmission-nat-pmp
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    env_file:
      - ./transmission.env
    volumes:
      - ./transmission-config:/config
      - /storage/downloads:/downloads
      - watch:/watch
    restart: unless-stopped
[...]
```
