### ISSUE TITLE
Docker compose configuration

### ISSUE THREAD

**Issue by hadim** [linuxserver/docker-transmission#27]
It works with version 48 and lower.

```
docker info
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   3a84010
 Built:        Thu Sep 22 15:56:00 2016
 OS/Arch:      linux/amd64
```

Logs look normal : 

```
Creating transmission
Attaching to transmission
transmission    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
transmission    | [s6-init] ensuring user provided files have correct perms...exited 0.
transmission    | [fix-attrs.d] applying ownership & permissions fixes...
transmission    | [fix-attrs.d] done.
transmission    | [cont-init.d] executing container initialization scripts...
transmission    | [cont-init.d] 10-adduser: executing... 
transmission    | 
transmission    | -------------------------------------
transmission    |           _     _ _
transmission    |          | |___| (_) ___
transmission    |          | / __| | |/ _ \ 
transmission    |          | \__ \ | | (_) |
transmission    |          |_|___/ |_|\___/
transmission    |                |_|
transmission    | 
transmission    | Brought to you by linuxserver.io
transmission    | We gratefully accept donations at:
transmission    | https://www.linuxserver.io/donations/
transmission    | -------------------------------------
transmission    | GID/UID
transmission    | -------------------------------------
transmission    | User uid:    0
transmission    | User gid:    0
transmission    | -------------------------------------
transmission    | 
transmission    | [cont-init.d] 10-adduser: exited 0.
transmission    | [cont-init.d] 20-config: executing... 
transmission    | [cont-init.d] 20-config: exited 0.
transmission    | [cont-init.d] done.
transmission    | [services.d] starting services
```

I have also similar issue with sickrage and couchpotato (radarr works fine) : for those images, the git clone fails (code 128).

ping @sparklyballs

**Comment by hadim** [comment]
What did you change between version 48 and 49 ?

**Comment by hadim** [comment]
Hum for docker-sickrage it works with version 46 and version 40 for docker-couchpotato. They all coincide with an alpine 3.5 rebase commit.

**Comment by hadim** [comment]
Here is the error I have with sickrage and couchpotato : 

```
sickrage        | python: can't open file '/app/sickrage/SickBeard.py': [Errno 2] No such file or directory
couchpotato     | python: can't open file '/app/couchpotato/CouchPotato.py': [Errno 2] No such file or directory
couchpotato     | python: can't open file '/app/couchpotato/CouchPotato.py': [Errno 2] No such file or directory
sickrage        | python: can't open file '/app/sickrage/SickBeard.py': [Errno 2] No such file or directory
couchpotato     | python: can't open file '/app/couchpotato/CouchPotato.py': [Errno 2] No such file or directory
sickrage        | python: can't open file '/app/sickrage/SickBeard.py': [Errno 2] No such file or directory
sickrage        | python: can't open file '/app/sickrage/SickBeard.py': [Errno 2] No such file or directory
couchpotato     | python: can't open file '/app/couchpotato/CouchPotato.py': [Errno 2] No such file or directory
```

Seems like the `git clone` command failed...

**Comment by hadim** [comment]
Here is the docker compose file I am using : 

```
transmission:
  container_name: transmission
  image: linuxserver/transmission:48
  volumes:
    - /share/Multimedia/Configurations/Transmission:/config
    - /share/Download:/downloads
  environment:
    - PGID=0
    - PUID=0
    - TZ=EST
  ports:
    - "9091:9091"
    - "51413:51413"

couchpotato:
  container_name: couchpotato
  #image: linuxserver/couchpotato
  build: docker-couchpotato
  volumes:
    - /share/Multimedia/Configurations/CouchPotato:/config
    - /share/Download:/downloads
    - /share/Multimedia/Movies:/movies
  environment:
    - PGID=0
    - PUID=0
    - TZ=EST
  ports:
    - "5050:5050"
  links:
    - transmission

sickrage:
  container_name: sickrage
  #image: linuxserver/sickrage
  build: docker-sickrage
  volumes:
    - /share/Multimedia/Configurations/SickRage:/config
    - /share/Download:/downloads
    - /share/Multimedia/Series:/tv
  environment:
    - PGID=0
    - PUID=0
    - TZ=EST
  ports:
    - "7073:8081"
  links:
    - transmission
```

Can you reproduce this issue ?
