### ISSUE TITLE
Can't connect to tracker

### ISSUE THREAD

**Issue by Ka0o0** [linuxserver/docker-transmission#62]
Hi,
I'm trying to use the docker image to have a torrent client on my server.
The server runs Fedora 28, SELinux permissive

When I add a torrent (official Ubuntu torrent) via web interface (access through proxy), I get `Could not connect to tracker` in the log files and the torrent won't start downloading. Network access is working as I can ping Google from inside the container.

I'm relatively new to Docker so I don't quite know how to debug the problem. Are any more steps required to get transmission working?
Any suggestions would be highly appreciated!

P.S: Here is my `docker-compose.yml`:

```
services:
  ...
  transmission:
    image: "linuxserver/transmission:latest"
    volumes:
      - /mnt/data/transmission/config:/config
      - /mnt/data/transmission/watch:/watch
      - /mnt/data/transmission/downloads:/downloads
    environment:
      - TZ="Europe/Vienna"
    restart: always
    ports:
      - 51413:51413
```

**Comment by sparklyballs** [comment]
you haven't set the PGID and PUID variables

https://github.com/linuxserver/docker-transmission/blob/master/README.md#user--group-identifiers

**Comment by Ka0o0** [comment]
My drive is owned by root so I updated the `docker–compose.yml` to:

```
services:
  ...
  transmission:
    image: "linuxserver/transmission:latest"
    volumes:
      - /mnt/data/transmission/config:/config
      - /mnt/data/transmission/watch:/watch
      - /mnt/data/transmission/downloads:/downloads
    environment:
      - TZ="Europe/Vienna"
      - PUID=0
      - PGID=0
    restart: always
    ports:
      - 51413:51413
```

which did not help.
But I found an additional error message 

```
UDP Failed to set receive buffer: requested 4194304, got 425984
UDP Please add the line "net.core.rmem_max = 4194304"

UDP Failed to set send buffer: requested 1048576, got 425984
UDP Please add the line "net.core.wmem_max = 1048576"
```

I did that and the error messages were gone and now it works

**Comment by Ammadkhalid** [comment]
@Ka0o0 i'm doing the same thing however when downloads are complete. Files just disappeared to somewhere than Downloads directory. Have you figure out your issue?
here is my docker-compose.yml
```
version: "3"

services:

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC
      - USER=transmission
      - PASS=transmission
    volumes:
#      - TODO dont forget to change volumes path.
      - ./docker/transmission/config:/config
      - ./data/media/transmission/:/downloads
      - ./docker/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  web:
    command: ['bash', './scripts/entry-point.sh']
    build: .
    volumes:
      - .:/code/
    depends_on:
      - transmission
    links:
      - transmission
```
